version: '3.7'

services:
  transactions-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    networks:
      - transactions_net
    ports:
      - 3307:3306
  transactions-api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - transactions-db
    networks:
      - transactions_net

networks:
  transactions_net:
    name: transactions_net
    driver: bridge
volumes:
  db_data:
